### PR TITLE
Make it possible to document sum types

### LINKED ISSUE #32: Doc Comments with `@sum_type`
I'm trying to run my project [PandemicAIs.jl](https://github.com/Laura7089/PandemicAis.jl) on commit e606d38. Adding the doc comment at line 13 of `src/PandemicAIs.jl` provokes the following error on project startup (paths have been clobbered):

```
$ julia --project -ie "using PandemicAIs"
[ Info: Precompiling PandemicAIs [5b8562fb-f4d8-4835-9d02-90268c707351]
ERROR: LoadError: cannot document the following expression:

#= /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:20 =# @sum_type PlayerAction{C} begin
        #= /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:21 =#
        Drive{C}(dest::C)
        #= /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:22 =#
        DirectFlight{C}(dest::C)
        #= /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:23 =#
        CharterFlight{C}(dest::C)
        #= /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:24 =#
        ShuttleFlight{C}(dest::C)
        #= /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:25 =#
        BuildStation
        #= /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:26 =#
        DiscoverCure{C}(dest::C, cards::Vector{C})
        #= /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:27 =#
        TreatDisease(target::Disease)
        #= /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:28 =#
        ShareKnowledge(player::Int)
        #= /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:29 =#
        Pass
    end

'@sum_type' not documentable. See 'Base.@__doc__' docs for details.

Stacktrace:
 [1] error(::String, ::String)
   @ Base ./error.jl:44
 [2] top-level scope
   @ /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:13
 [3] include
   @ ./Base.jl:457 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2010
 [5] top-level scope
   @ stdin:2
in expression starting at /fake_path/PandemicAIs.jl/src/PandemicAIs.jl:1
in expression starting at stdin:2
ERROR: Failed to precompile PandemicAIs [5b8562fb-f4d8-4835-9d02-90268c707351] to "/home/laura/.julia/compiled/v1.9/PandemicAIs/jl_yf04M3".
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:2260
 [3] compilecache
   @ ./loading.jl:2127 [inlined]
 [4] _require(pkg::Base.PkgId, env::String)
   @ Base ./loading.jl:1770
 [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
   @ Base ./loading.jl:1625
 [6] macro expansion
   @ ./loading.jl:1613 [inlined]
 [7] macro expansion
   @ ./lock.jl:267 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1576%
```

Is it not possible to document the `@sum_types` declaration, or have I missed something?

### PR DESCRIPTION
**Pull request by Tortar**
Fixes #32

### CODE REVIEW

**Comment by Tortar** [comment]
Fails on nightly, but I guess this is a Julia bug

**Comment by MasonProtter** [comment]
Oh I didn't realize it was so simple to support docstrings!

**Comment by MasonProtter** [comment]
Interesting that this doesn't work on Master, would you mind filing an issue in the upstream julia repo?

**Comment by Tortar** [comment]
yeah, I tried to reduce it but with no avail.

I will point to the ci in this pr then :-)

**Pull request merged**
